loc_city = "Munich"                    # Enter your city name (this is for the weather)
loc_region = "Germany"                 # Enter either your state or country
weather_location = "Munich"
news_count = 2                         # How many news stories Vector should read (max is 7 to 9)
vector_mood = "normal"                 # Normal is the only mood at the moment
temperature = "metric"                 # Enter "imperial" or "metric"
chattiness = 6                         # Enter a number between "1" and "10". The number "5" is average. ("10" is VERY chatty.) This feature still needs work.
sound_volume = 1                       # Vector's sound effects between "1" and "5". (5 is very loud)
voice_volume = 2                       # Vector's voice volume between "1" and "5". (5 is very loud)
news_feed = "https://www.tagesschau.de/xml/rss2" # You can use any rss feed for this
mail_imap = "imap.gmail.com"           # a imap server
mail_account = "xxxxxx@googlemail.com" # the email that should be checked
mail_pw = "somecleverpassword"         # the password for the e-mail